# -*- coding: utf-8 -*-
"""CHAT BOT(Proyecto_FREElance _3322S33_2025)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ydVLumUn5zibEh_prACm96R6rDDkxUJ
"""

# Chatbot sencillo preguntas basicas

def responder(pregunta):
    pregunta = pregunta.lower()  # Pasar a minúsculas para comparar
    if "hola" in pregunta:
        return "¡Holiis! ¿Cómo puedo ayudarte?"
    elif "buenas" in pregunta or "chao" in pregunta:
        return  "¡Hasta luuuego!"
    elif "adiós" in pregunta or "chao" in pregunta:
        return "¡Hasta luuuego! Que tengas un buen día."
    elif "nombre" in pregunta:
        return "Soy un chatbot de ejemplo. ¡Encantado!"
    elif "ayuda" in pregunta:
        return "Claro, ¿en qué tema necesitas ayuda?"
    else:
        return "Lo siento, no entiendo tu pregunta."

# Loop de conversación
while True:
    user_input = input("Tú: ")
    if user_input.lower() in ["salir", "exit", "quit"]:
        print("Bot: ¡Adiós!")
        break
    respuesta = responder(user_input)
    print("Bot:", respuesta)

